export default {
    data() {
        return {
            froala_config: function () {
                const runtimeConfig = useRuntimeConfig();
                return {
                    height: 300,
                    // inlineMode: false,
                    pastePlain: false,
                    paragraphy: false,
                    quickInsertEnabled: false,
                    toolbarButtons: [
                        "undo",
                        "redo",
                        "fullscreen",
                        "|",
                        "fontSize",
                        "textColor",
                        "backgroundColor",
                        "color",
                        "bold",
                        "italic",
                        "underline",
                        "inlineClass",
                        "subscript",
                        "superscript",
                        "|",
                        "paragraphFormat",
                        "align",
                        "outdent",
                        "indent",
                        "|",
                        "formatOL",
                        "formatUL",
                        "quote",
                        "-",
                        "insertLink",
                        "insertImage",
                        "insertVideo",
                        "insertFile",
                        "insertTable",
                        "|",
                        "insertHR",
                        "selectAll",
                        "clearFormatting",
                        "|",
                        "print",
                        "getPDF",
                        "html",
                        // "codeBeautifier",
                        "wirisEditor",
                        "wirisChemistry",
                        "fontAwesome",
                    ],
                    // faButtons: ["fontAwesomeBack", "|"],
                    // Change buttons for XS screen.
                    toolbarButtonsXS: [
                        ["undo", "redo"],
                        [
                            "bold",
                            "italic",
                            "underline",
                            "subscript",
                            "superscript",
                        ],
                    ],
                    htmlAllowedTags: ['.*','i', 'em', 'strong', 'a', 'br', 'ul', 'li'],
                    htmlAllowedAttrs: ['.*','class', 'href', 'target', 'style'],
                    
                    // htmlAllowedEmptyTags: ["mprescripts", "none"],
                    placeholderText: "",
                    attribution: false,
                    key: "enter-your-license-key-here",
                    disableRightClick: true,
                    imageUploadURL: `${runtimeConfig.public.apiBase}/froala/image`,
                    imageAllowedTypes: ["jpeg", "jpg", "png"],
                    fileUploadURL: `${runtimeConfig.public.apiBase}/froala/document`,
                    videoUploadURL: `${runtimeConfig.public.apiBase}/froala/video`,
                    // fileUpload: false,
                    // imageUpload: false,
                    imagePaste: false,
                    imagePasteProcess: false,
                    imageResize: true,
                    crossDomain: true,
                    pasteAllowedStyleProps: ["*"],
                    pasteAllowLocalImages: true,
                    htmlAllowComments: true,
                    htmlExecuteScripts: true,
                    fontSizeSelection: true,
                    fontSizeDefaultSelection: "18",
                };
            },
        };
    },
};
